/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PixiDevtoolsRouteImport } from './routes/pixi-devtools'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinSessionRouteImport } from './routes/join-session'
import { Route as EditorSessionRouteImport } from './routes/editor-session'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerSessionMatchIdRouteImport } from './routes/player-session.$match-id'
import { Route as DmSessionMatchIdRouteImport } from './routes/dm-session.$match-id'

const PixiDevtoolsRoute = PixiDevtoolsRouteImport.update({
  id: '/pixi-devtools',
  path: '/pixi-devtools',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinSessionRoute = JoinSessionRouteImport.update({
  id: '/join-session',
  path: '/join-session',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorSessionRoute = EditorSessionRouteImport.update({
  id: '/editor-session',
  path: '/editor-session',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerSessionMatchIdRoute = PlayerSessionMatchIdRouteImport.update({
  id: '/player-session/$match-id',
  path: '/player-session/$match-id',
  getParentRoute: () => rootRouteImport,
} as any)
const DmSessionMatchIdRoute = DmSessionMatchIdRouteImport.update({
  id: '/dm-session/$match-id',
  path: '/dm-session/$match-id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor-session': typeof EditorSessionRoute
  '/join-session': typeof JoinSessionRoute
  '/login': typeof LoginRoute
  '/pixi-devtools': typeof PixiDevtoolsRoute
  '/dm-session/$match-id': typeof DmSessionMatchIdRoute
  '/player-session/$match-id': typeof PlayerSessionMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor-session': typeof EditorSessionRoute
  '/join-session': typeof JoinSessionRoute
  '/login': typeof LoginRoute
  '/pixi-devtools': typeof PixiDevtoolsRoute
  '/dm-session/$match-id': typeof DmSessionMatchIdRoute
  '/player-session/$match-id': typeof PlayerSessionMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor-session': typeof EditorSessionRoute
  '/join-session': typeof JoinSessionRoute
  '/login': typeof LoginRoute
  '/pixi-devtools': typeof PixiDevtoolsRoute
  '/dm-session/$match-id': typeof DmSessionMatchIdRoute
  '/player-session/$match-id': typeof PlayerSessionMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editor-session'
    | '/join-session'
    | '/login'
    | '/pixi-devtools'
    | '/dm-session/$match-id'
    | '/player-session/$match-id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editor-session'
    | '/join-session'
    | '/login'
    | '/pixi-devtools'
    | '/dm-session/$match-id'
    | '/player-session/$match-id'
  id:
    | '__root__'
    | '/'
    | '/editor-session'
    | '/join-session'
    | '/login'
    | '/pixi-devtools'
    | '/dm-session/$match-id'
    | '/player-session/$match-id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorSessionRoute: typeof EditorSessionRoute
  JoinSessionRoute: typeof JoinSessionRoute
  LoginRoute: typeof LoginRoute
  PixiDevtoolsRoute: typeof PixiDevtoolsRoute
  DmSessionMatchIdRoute: typeof DmSessionMatchIdRoute
  PlayerSessionMatchIdRoute: typeof PlayerSessionMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pixi-devtools': {
      id: '/pixi-devtools'
      path: '/pixi-devtools'
      fullPath: '/pixi-devtools'
      preLoaderRoute: typeof PixiDevtoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-session': {
      id: '/join-session'
      path: '/join-session'
      fullPath: '/join-session'
      preLoaderRoute: typeof JoinSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor-session': {
      id: '/editor-session'
      path: '/editor-session'
      fullPath: '/editor-session'
      preLoaderRoute: typeof EditorSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player-session/$match-id': {
      id: '/player-session/$match-id'
      path: '/player-session/$match-id'
      fullPath: '/player-session/$match-id'
      preLoaderRoute: typeof PlayerSessionMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dm-session/$match-id': {
      id: '/dm-session/$match-id'
      path: '/dm-session/$match-id'
      fullPath: '/dm-session/$match-id'
      preLoaderRoute: typeof DmSessionMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorSessionRoute: EditorSessionRoute,
  JoinSessionRoute: JoinSessionRoute,
  LoginRoute: LoginRoute,
  PixiDevtoolsRoute: PixiDevtoolsRoute,
  DmSessionMatchIdRoute: DmSessionMatchIdRoute,
  PlayerSessionMatchIdRoute: PlayerSessionMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
